packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^4.16.1
  '@fanoosjs/core': workspac
  '@iconify-json/lucide': ^1.2.58
  '@iconify-json/material-icon-theme': ^1.2.16
  '@iconify-json/material-symbols': ^1.2.30
  '@iconify-json/vscode-icons': ^1.2.23
  '@nuxt/content': ^3.6.3
  '@nuxt/icon': ^1.15.0
  '@nuxt/ui-pro': ^3.3.0
  '@tailwindcss/vite': ^4.1.11
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.0.7
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/eslint-plugin': ^1.3.3
  automd: ^0.4.0
  changelogen: ^0.6.1
  commander: ^14.0.0
  eslint: ^9.30.0
  fs-extra: ^11.3.0
  globby: ^14.1.0
  i: ^0.3.7
  npm: ^11.5.1
  nuxt: ^4.0.0
  nuxt-typed-router: ^4.0.1
  oxc-parser: ^0.75.1
  oxc-walker: ^0.3.0
  reka-ui: ^2.4.0
  shiki: ^3.8.1
  tailwindcss: ^4.1.11
  tsdown: ^0.12.9
  typescript: ^5.8.3
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-router: ^4.5.1
