packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.3.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.3.1
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/eslint-plugin': ^1.3.9
  automd: ^0.4.0
  changelogen: ^0.6.2
  commander: ^14.0.0
  eslint: ^9.35.0
  fs-extra: ^11.3.1
  globby: ^14.1.0
  oxc-parser: ^0.87.0
  oxc-walker: ^0.5.2
  tsdown: ^0.15.0
  typescript: ^5.9.2
  vitest: ^3.2.4
