packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^4.16.1
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.0.7
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/eslint-plugin': ^1.3.3
  automd: ^0.4.0
  changelogen: ^0.6.1
  eslint: ^9.30.0
  fs-extra: ^11.3.0
  globby: ^14.1.0
  oxc-parser: ^0.75.0
  tsdown: ^0.12.9
  typescript: ^5.8.3
  vitest: ^3.2.4
